import { getTokenData } from "@/utils/verifyToken";
import { cookies } from "next/headers";
import { redirect } from "next/navigation";

export const metadata = {
  title: "CinemaMSN",
  description: "Generated by create next app",
  icons: {
    icon: "/images/icon-01.png"
  },
};

export default async function DashboardLayout({ children }) {
	const getCookies = await cookies();
	const token = getCookies.get("jwtToken")?.value || null;
	const userData = getTokenData(token);
	if (userData?.isAdmin == "admin" || userData?.isAdmin == "helper") {
		return (
			<>
				{children}
			</>
		);
	} else {
		redirect('/');
	}
}